-- ============================================================================
-- Seed: Feeling Keywords
-- ----------------------------------------------------------------------------
-- Insère les mots-clés de ressenti prédéfinis (admin)
-- À exécuter après la migration migration-feeling-keywords.sql
-- ============================================================================
-- Insérer les mots-clés (avec ON CONFLICT pour éviter les doublons)
-- Les slugs sont générés manuellement pour éviter les dépendances d'extensions
INSERT INTO public.feeling_keywords (label, slug, source, created_by)
VALUES ('Émouvant', 'emouvant', 'admin', NULL),
    ('Captivant', 'captivant', 'admin', NULL),
    ('Drôle', 'drole', 'admin', NULL),
    ('Déstabilisant', 'destabilisant', 'admin', NULL),
    ('Inspirant', 'inspirant', 'admin', NULL),
    ('Poétique', 'poetique', 'admin', NULL),
    ('Violent', 'violent', 'admin', NULL),
    ('Contemplatif', 'contemplatif', 'admin', NULL),
    ('Anxiogène', 'anxiogene', 'admin', NULL),
    ('Réconfortant', 'reconfortant', 'admin', NULL),
    ('Percutant', 'percutant', 'admin', NULL),
    ('Sombre', 'sombre', 'admin', NULL),
    ('Envoûtant', 'envoutant', 'admin', NULL),
    ('Bouleversant', 'bouleversant', 'admin', NULL),
    ('Intrigant', 'intrigant', 'admin', NULL),
    ('Mystérieux', 'mysterieux', 'admin', NULL),
    ('Hypnotique', 'hypnotique', 'admin', NULL),
    ('Époustouflant', 'epoustouflant', 'admin', NULL),
    ('Lancinant', 'lancinant', 'admin', NULL),
    ('Électrisant', 'electrisant', 'admin', NULL),
    ('Énigmatique', 'enigmatique', 'admin', NULL),
    ('Profond', 'profond', 'admin', NULL),
    ('Doux-amer', 'doux-amer', 'admin', NULL),
    ('Grisant', 'grisant', 'admin', NULL),
    ('Oppressant', 'oppressant', 'admin', NULL),
    ('Déchirant', 'dechirant', 'admin', NULL),
    ('Lumineux', 'lumineux', 'admin', NULL),
    ('Onirique', 'onirique', 'admin', NULL),
    ('Rythmé', 'rythme', 'admin', NULL),
    ('Énergisant', 'energisant', 'admin', NULL),
    ('Glacial', 'glacial', 'admin', NULL),
    ('Chaleureux', 'chaleureux', 'admin', NULL),
    ('Dissonant', 'dissonant', 'admin', NULL),
    ('Dérangeant', 'derangeant', 'admin', NULL),
    ('Léger', 'leger', 'admin', NULL),
    ('Puissant', 'puissant', 'admin', NULL),
    ('Subtil', 'subtil', 'admin', NULL),
    ('Immersif', 'immersif', 'admin', NULL),
    ('Rassurant', 'rassurant', 'admin', NULL),
    ('Étrange', 'etrange', 'admin', NULL),
    ('Saisissant', 'saisissant', 'admin', NULL),
    ('Revigorant', 'revigorant', 'admin', NULL),
    ('Tragique', 'tragique', 'admin', NULL),
    ('Fiévreux', 'fievreux', 'admin', NULL),
    ('Intense', 'intense', 'admin', NULL),
    ('Palpitant', 'palpitant', 'admin', NULL),
    ('Bouillant', 'bouillant', 'admin', NULL),
    ('Fulgurant', 'fulgurant', 'admin', NULL),
    ('Dévastateur', 'devastateur', 'admin', NULL),
    ('Renversant', 'renversant', 'admin', NULL),
    ('Exaltant', 'exaltant', 'admin', NULL),
    ('Éprouvant', 'eprouvant', 'admin', NULL),
    ('Étourdissant', 'etourdissant', 'admin', NULL),
    ('Ravageur', 'ravageur', 'admin', NULL),
    ('Tourmenté', 'tourmente', 'admin', NULL),
    ('Vibrant', 'vibrant', 'admin', NULL),
    ('Mélancolique', 'melancolique', 'admin', NULL),
    ('Apaisant', 'apaisant', 'admin', NULL),
    ('Délicat', 'delicat', 'admin', NULL),
    ('Brumeux', 'brumeux', 'admin', NULL),
    ('Velouté', 'veloute', 'admin', NULL),
    ('Doucereux', 'doucereux', 'admin', NULL),
    ('Paisible', 'paisible', 'admin', NULL),
    ('Flottant', 'flottant', 'admin', NULL),
    ('Moelleux', 'moelleux', 'admin', NULL),
    ('Lisse', 'lisse', 'admin', NULL),
    ('Tendre', 'tendre', 'admin', NULL) ON CONFLICT (slug) DO NOTHING;
-- Vérifier le nombre de mots-clés insérés
SELECT COUNT(*) as total_keywords
FROM public.feeling_keywords
WHERE source = 'admin';